os: linux
dist: bionic
language: python
git:
  depth: false
services:
  - docker

stages:
  - name: test

before_install:
  - set -e
  - . ci/common

install:
  # Setup our k3s based Kubernetes cluster and use its kubectl as well
  - setup_hosts
  - setup_k3d
  - setup_kubectl
  - setup_helm
script:
  - helm lint shinyproxy
  - helm install shiny ./shinyproxy --values $CONFIG_FILE
  - await_shinyproxy
  - pip install --no-cache-dir -r dev-requirements.txt
  - pytest --verbose --exitfirst ./tests
env:
  jobs:
    - K3S_VERSION=v1.18.6-k3s1 CONFIG_FILE=test-values.yaml
    - K3S_VERSION=v1.17.9-k3s1 CONFIG_FILE=test-values.yaml
    - K3S_VERSION=v1.16.13-k3s1 CONFIG_FILE=test-values.yaml
  global:
    - HELM_VERSION=v3.4.1
    - K3D_VERSION=v1.7.0

