name: Build and push Docker image
on:
  workflow_dispatch:
  push:
    paths:
      - 'shinyproxy/Chart.yaml'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mikefarah/yq@v4.25.2
      id: yq
      with:
        cmd: yq eval '.appVersion' shinyproxy/Chart.yaml
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: images
        push: true
        build-args: |
          SHINYPROXY_VERSION=${{ steps.yq.outputs.result }}
        tags: remche/shinyproxy:${{ steps.yq.outputs.result }}
